# Generated by Django 5.0.2 on 2024-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('description', models.TextField()),
                ('participants', models.TextField()),
            ],
        ),
    ]
