# Generated by Django 5.0.2 on 2024-02-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
